const TOTAL_WEEKS = 7;

export type GalleryPhoto = {
  id: number;
  alt: string;
  aspect: number;
};

export type GalleryWeekKey = `week-${number}`;

export type GalleryWeeks = Record<GalleryWeekKey, GalleryPhoto[]>;

const weekKey = (n: number): GalleryWeekKey => `week-${n}`;

export const galleryImagePath = (weekKey: string, photoId: number): string =>
  `/images/gallery/${weekKey}/${photoId}.webp`;

const weeks: GalleryWeeks = {
  "week-1": [
    { id: 1, alt: "Sibolga week 1", aspect: 1.78 },
    { id: 2, alt: "Sibolga week 1", aspect: 1.78 },
    { id: 3, alt: "Sibolga week 1", aspect: 1.78 },
    { id: 4, alt: "Sibolga week 1", aspect: 1.5 },
    { id: 5, alt: "Sibolga week 1", aspect: 0.56 },
    { id: 6, alt: "Sibolga week 1", aspect: 1.77 },
    { id: 7, alt: "Sibolga week 1", aspect: 0.56 },
    { id: 8, alt: "Sibolga week 1", aspect: 1.5 },
    { id: 9, alt: "Sibolga week 1", aspect: 1.5 },
    { id: 10, alt: "Sibolga week 1", aspect: 1.78 },
    { id: 11, alt: "Sibolga week 1", aspect: 1.78 },
    { id: 12, alt: "Sibolga week 1", aspect: 1.78 },
    { id: 13, alt: "Sibolga week 1", aspect: 1.78 },
    { id: 14, alt: "Sibolga week 1", aspect: 1.33 },
    { id: 15, alt: "Sibolga week 1", aspect: 0.75 },
    { id: 16, alt: "Sibolga week 1", aspect: 1.78 },
    { id: 17, alt: "Sibolga week 1", aspect: 1.78 },
  ],
  "week-2": [
    { id: 1, alt: "Sibolga week 2", aspect: 1.5 },
    { id: 3, alt: "Sibolga week 2", aspect: 1.5 },
    { id: 4, alt: "Sibolga week 2", aspect: 1.5 },
    { id: 5, alt: "Sibolga week 2", aspect: 1.5 },
    { id: 6, alt: "Sibolga week 2", aspect: 1.78 },
    { id: 7, alt: "Sibolga week 2", aspect: 1.5 },
    { id: 8, alt: "Sibolga week 2", aspect: 1.33 },
    { id: 9, alt: "Sibolga week 2", aspect: 1.33 },
    { id: 10, alt: "Sibolga week 2", aspect: 1.5 },
    { id: 11, alt: "Sibolga week 2", aspect: 1.5 },
    { id: 12, alt: "Sibolga week 2", aspect: 1.33 },
    { id: 13, alt: "Sibolga week 2", aspect: 1.5 },
  ],
  "week-3": [
    { id: 1, alt: "Sibolga week 3", aspect: 1.78 },
    { id: 2, alt: "Sibolga week 3", aspect: 1.78 },
    { id: 3, alt: "Sibolga week 3", aspect: 1.78 },
    { id: 4, alt: "Sibolga week 3", aspect: 1.78 },
    { id: 5, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 6, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 7, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 8, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 9, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 10, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 11, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 12, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 13, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 14, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 15, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 16, alt: "Sibolga week 3", aspect: 1.5 },
    { id: 17, alt: "Sibolga week 3", aspect: 0.67 },
  ],
  "week-4": [
    { id: 1, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 2, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 3, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 4, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 5, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 6, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 7, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 8, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 9, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 10, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 11, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 12, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 13, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 14, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 15, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 16, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 17, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 18, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 19, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 20, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 21, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 22, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 23, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 24, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 25, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 26, alt: "Sibolga week 4", aspect: 1.5 },
    { id: 27, alt: "Sibolga week 4", aspect: 1.5 },
  ],
  "week-5": [
    { id: 1, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 2, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 3, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 4, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 5, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 6, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 7, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 8, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 9, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 10, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 11, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 12, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 13, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 14, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 15, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 16, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 17, alt: "Sibolga week 5", aspect: 1.78 },
    { id: 18, alt: "Sibolga week 5", aspect: 1.78 },
    { id: 19, alt: "Sibolga week 5", aspect: 1.78 },
    { id: 20, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 21, alt: "Sibolga week 5", aspect: 0.67 },
    { id: 22, alt: "Sibolga week 5", aspect: 1.5 },
    { id: 23, alt: "Sibolga week 5", aspect: 1.78 },
    { id: 24, alt: "Sibolga week 5", aspect: 1.78 },
    { id: 25, alt: "Sibolga week 5", aspect: 0.75 },
    { id: 26, alt: "Sibolga week 5", aspect: 0.75 },
  ],
  "week-6": [
    { id: 1, alt: "Sibolga week 6", aspect: 1.5 },
    { id: 2, alt: "Sibolga week 6", aspect: 1.5 },
    { id: 3, alt: "Sibolga week 6", aspect: 1.5 },
    { id: 4, alt: "Sibolga week 6", aspect: 1.5 },
    { id: 5, alt: "Sibolga week 6", aspect: 2 },
    { id: 6, alt: "Sibolga week 6", aspect: 1.5 },
    { id: 7, alt: "Sibolga week 6", aspect: 1.5 },
    { id: 8, alt: "Sibolga week 6", aspect: 1.5 },
    { id: 9, alt: "Sibolga week 6", aspect: 0.67 },
    { id: 10, alt: "Sibolga week 6", aspect: 1.5 },
    { id: 11, alt: "Sibolga week 6", aspect: 1.78 },
    { id: 12, alt: "Sibolga week 6", aspect: 1.78 },
    { id: 13, alt: "Sibolga week 6", aspect: 1.78 },
    { id: 14, alt: "Sibolga week 6", aspect: 1.78 },
    { id: 15, alt: "Sibolga week 6", aspect: 1.78 },
    { id: 16, alt: "Sibolga week 6", aspect: 1.33 },
    { id: 17, alt: "Sibolga week 6", aspect: 1.5 },
    { id: 18, alt: "Sibolga week 6", aspect: 1.5 },
  ],
  "week-7": [
    { id: 1, alt: "Sibolga week 7", aspect: 0.56 },
    { id: 2, alt: "Sibolga week 7", aspect: 1.78 },
    { id: 3, alt: "Sibolga week 7", aspect: 1.78 },
    { id: 4, alt: "Sibolga week 7", aspect: 1.33 },
    { id: 5, alt: "Sibolga week 7", aspect: 1.5 },
    { id: 6, alt: "Sibolga week 7", aspect: 1.5 },
    { id: 7, alt: "Sibolga week 7", aspect: 1.5 },
    { id: 8, alt: "Sibolga week 7", aspect: 1.5 },
    { id: 9, alt: "Sibolga week 7", aspect: 1.5 },
    { id: 10, alt: "Sibolga week 7", aspect: 1.5 },
    { id: 11, alt: "Sibolga week 7", aspect: 1.33 },
    { id: 12, alt: "Sibolga week 7", aspect: 1.33 },
    { id: 13, alt: "Sibolga week 7", aspect: 1.33 },
    { id: 14, alt: "Sibolga week 7", aspect: 1.33 },
    { id: 15, alt: "Sibolga week 7", aspect: 1.33 },
    { id: 16, alt: "Sibolga week 7", aspect: 0.67 },
    { id: 17, alt: "Sibolga week 7", aspect: 0.67 },
    { id: 18, alt: "Sibolga week 7", aspect: 1.5 },
    { id: 19, alt: "Sibolga week 7", aspect: 1.5 },
    { id: 20, alt: "Sibolga week 7", aspect: 1.5 },
    { id: 21, alt: "Sibolga week 7", aspect: 1.5 },
    { id: 22, alt: "Sibolga week 7", aspect: 1.5 },
    { id: 23, alt: "Sibolga week 7", aspect: 1.5 },
  ],
};

export function getWeekPhotos(key: GalleryWeekKey): GalleryPhoto[] {
  return weeks[key] ?? [];
}

export function getAllWeekKeys(): GalleryWeekKey[] {
  return Array.from({ length: TOTAL_WEEKS }, (_, i) => weekKey(i + 1));
}
